services:
  db-mysql:
    image: mysql
    ports:
      -  "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - net-deploy

  backend:
    image: python
    command: tail -f /dev/null
    ports: 
      - "8000:8000"
    volumes:
      - /home/adrian/bunker4/projectFinal/backend:/app
    networks:
            - net-deploy

  react-server:
    image: node
    command: tail -f /dev/null
    ports:
      - "3000:3000"
    volumes:
      - /home/adrian/fullstack/react-proyectos/pildorasReact/react-docker:/app
    networks:
            - net-deploy
    
networks:
  net-deploy:
    name: net-deploy
      
